"""change length of string for title

Revision ID: 16256831f4a0
Revises: b74af5c2b02c
Create Date: 2021-10-26 21:41:48.351066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16256831f4a0'
down_revision = 'b74af5c2b02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('capstone_info_advisor_id_fkey', 'capstone_info', type_='foreignkey')
    op.drop_column('capstone_info', 'advisor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capstone_info', sa.Column('advisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('capstone_info_advisor_id_fkey', 'capstone_info', 'users', ['advisor_id'], ['id'])
    # ### end Alembic commands ###
