"""empty message

Revision ID: 2ff3e2b21f9c
Revises: 007f446bb1ef
Create Date: 2021-10-26 09:54:07.348001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff3e2b21f9c'
down_revision = '007f446bb1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'no')
    # ### end Alembic commands ###
