"""empty message

Revision ID: a1da1cca97f9
Revises: a5c3990cc94b
Create Date: 2021-10-26 10:06:42.394996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1da1cca97f9'
down_revision = 'a5c3990cc94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'no')
    op.drop_column('books', 'yes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('yes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('no', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
