"""empty message

Revision ID: 2e5679e3d02f
Revises: 4decc3bb3a99
Create Date: 2022-03-02 20:18:17.007926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5679e3d02f'
down_revision = '4decc3bb3a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('advisor', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('skills_offering', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('skills_requesting', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('class_year', sa.Enum('M19', 'M20', 'M21', 'M22', 'M23', 'M24', 'M25', 'M26', name='classenum'), nullable=True))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'class_year')
    op.drop_column('users', 'name')
    op.drop_column('projects', 'location')
    op.drop_column('projects', 'skills_requesting')
    op.drop_column('projects', 'skills_offering')
    op.drop_column('projects', 'advisor')
    op.drop_column('projects', 'skills')
    # ### end Alembic commands ###
