"""empty message

Revision ID: 444121fafe9b
Revises: 98a8989cdc95
Create Date: 2021-10-29 18:58:16.612486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444121fafe9b'
down_revision = '98a8989cdc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capstone_info_last_updated', table_name='capstone_info')
    op.drop_table('capstone_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capstone_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('abstract', sa.VARCHAR(), nullable=True),
    sa.Column('keywords', sa.VARCHAR(), nullable=True),
    sa.Column('feature', sa.VARCHAR(length=18), nullable=True),
    sa.Column('los', sa.VARCHAR(), nullable=True),
    sa.Column('custom_los', sa.VARCHAR(), nullable=True),
    sa.Column('hsr_review', sa.VARCHAR(length=12), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capstone_info_last_updated', 'capstone_info', ['last_updated'], unique=False)
    # ### end Alembic commands ###
