"""empty message

Revision ID: 4951779191d0
Revises: eecab1c992f7
Create Date: 2021-11-23 08:23:26.952170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4951779191d0'
down_revision = 'eecab1c992f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('public_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'public_id')
    # ### end Alembic commands ###
