"""empty message

Revision ID: 4decc3bb3a99
Revises: 444121fafe9b
Create Date: 2021-12-02 11:24:17.943584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4decc3bb3a99'
down_revision = '444121fafe9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('public_id', sa.Integer(), nullable=True))
    op.add_column('logins', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('logins', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('logins', 'password')
    op.drop_column('logins', 'public_id')
    # ### end Alembic commands ###
