"""empty message

Revision ID: 55672c6a1ae9
Revises: afd0d25af529
Create Date: 2022-03-04 22:34:56.786439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55672c6a1ae9'
down_revision = 'afd0d25af529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('__ts_vector__', models.TSVector(), sa.Computed("to_tsvector('english', name || ' ' || class_year || ' ' || primary_major || ' ' || secondary_major || ' ' || primary_concentration || ' ' || secondary_concentration || ' ' || special_concentration || ' ' || minor || ' ' || minor_concentration)", persisted=True), nullable=True))
    op.create_index('ix_users__ts_vector__', 'users', ['__ts_vector__'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users__ts_vector__', table_name='users', postgresql_using='gin')
    op.drop_column('users', '__ts_vector__')
    # ### end Alembic commands ###
