"""create tables

Revision ID: adf9461b32b9
Revises: 16256831f4a0
Create Date: 2021-10-26 21:44:21.116334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf9461b32b9'
down_revision = '16256831f4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logins_email'), 'logins', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=128), nullable=True),
    sa.Column('lastname', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('advisor', 'student', name='roleenum'), nullable=True),
    sa.Column('primary_major', sa.Enum('CS', 'BS', 'NS', 'AH', 'SS', name='collegeenum'), nullable=True),
    sa.Column('secondary_major', sa.Enum('CS', 'BS', 'NS', 'AH', 'SS', name='collegeenum'), nullable=True),
    sa.Column('primary_concentration', sa.Enum('APS', 'AL', 'BM', 'CO', 'CBB', 'CTA', 'CSAI', 'CKD', 'DSS', 'DS', 'ES', 'ECS', 'EASS', 'EM', 'HFC', 'HAN', 'HAP', 'HFD', 'MOC', 'MATH', 'MA', 'NBV', 'PEL', 'PGS', 'PSCS', 'RANS', 'SG', 'SF', 'TFNS', 'TASS', 'CSC', name='concentrationenum'), nullable=True),
    sa.Column('secondary_concentration', sa.Enum('APS', 'AL', 'BM', 'CO', 'CBB', 'CTA', 'CSAI', 'CKD', 'DSS', 'DS', 'ES', 'ECS', 'EASS', 'EM', 'HFC', 'HAN', 'HAP', 'HFD', 'MOC', 'MATH', 'MA', 'NBV', 'PEL', 'PGS', 'PSCS', 'RANS', 'SG', 'SF', 'TFNS', 'TASS', 'CSC', name='concentrationenum'), nullable=True),
    sa.Column('special_concentration', sa.String(), nullable=True),
    sa.Column('minor', sa.Enum('CS', 'BS', 'NS', 'AH', 'SS', name='collegeenum'), nullable=True),
    sa.Column('minor_concentration', sa.Enum('APS', 'AL', 'BM', 'CO', 'CBB', 'CTA', 'CSAI', 'CKD', 'DSS', 'DS', 'ES', 'ECS', 'EASS', 'EM', 'HFC', 'HAN', 'HAP', 'HFD', 'MOC', 'MATH', 'MA', 'NBV', 'PEL', 'PGS', 'PSCS', 'RANS', 'SG', 'SF', 'TFNS', 'TASS', 'CSC', name='concentrationenum'), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capstone_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('feature', sa.Enum('creative', 'primary_research', 'secondary_research', 'replication', 'interview_survey', 'data_analysis', 'journalism', 'philosophical', 'policy', 'education', 'business', 'podcast', 'app', 'other', name='featureenum'), nullable=True),
    sa.Column('los', sa.String(), nullable=True),
    sa.Column('custom_los', sa.String(), nullable=True),
    sa.Column('hsr_review', sa.Enum('not_yet', 'awaiting', 'revising', 'not_reviewed', 'reviewed', 'submitted', 'confirmed', 'not_granted', 'na', 'other', name='hsrenum'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capstone_info_last_updated'), 'capstone_info', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capstone_info_last_updated'), table_name='capstone_info')
    op.drop_table('capstone_info')
    op.drop_table('users')
    op.drop_index(op.f('ix_logins_email'), table_name='logins')
    op.drop_table('logins')
    # ### end Alembic commands ###
