"""empty message

Revision ID: d3fa4c215134
Revises: 4decc3bb3a99
Create Date: 2022-02-19 14:51:19.760131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fa4c215134'
down_revision = '4decc3bb3a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('feature', sa.String(), nullable=True))
    op.drop_column('projects', 'features')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('features', sa.VARCHAR(), nullable=True))
    op.drop_column('projects', 'feature')
    # ### end Alembic commands ###
